export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_SEARCH_TITLE = 'SET_SEARCH_TITLE';
export const SET_LANGUAGE = 'SET_LANGUAGE';